### ISSUE TITLE
Probe on another server

### ISSUE THREAD

**Issue by Chriszep76** [vMarkusK/Advanced-PRTG-Sensors#101]
Good Morning
-Veeam12 last version installed on ip 192.168.102.4 
-Prtg on another server (different login)
I tried this parameter on the sensor : -p=“192.168.102.4“
can i put user and password on this line ??

![2023-08-10 13_49_11-Veeam Backup _ Sensor Details _ PRTG Network Monitor (AVRPRTG)](https://github.com/vMarkusK/Advanced-PRTG-Sensors/assets/119064415/da3bf761-03d0-41b4-8318-2468f60d7ece)

**Comment by vMarkusK** [comment]
Passing username/password as parameter is not supported.

Use a windows task in combination with http-push or modify the Probe service to use a valid credential.

**Comment by vMarkusK** [comment]
Prefered setup is http-push

`PRTG-VeeamBRStats-v3.ps1 -httppush:$true -httpserver 10.10.10.10 -httptoken 24A26A91-D292-4FF7-895D-B5E128A4D6C9 -httpport 5050`

**Comment by Chriszep76** [comment]
thanks for our fast answer
