### ISSUE TITLE
Advanced-PRTG-Sensors - Error PE132

### ISSUE THREAD

**Issue by antonin78** [vMarkusK/Advanced-PRTG-Sensors#50]
Good morning, sir,

I tried to set up your sensor. 

However, I end up with a PE132 error telling me that the response format is incorrect.

Do you have a lead?

I'm using PSx64.exe to run the script, I did accept unsigned scripts on PowerShell, and the Veeam console is on the server and working properly.
PRTG is installed on a dedicated virtual machine and the Veeam database is on a server on the local network.

I have the impression that PRTG does not understand the output of the program and cannot create the sensors in competence.

Thank you in advance for your help!

![image](https://user-images.githubusercontent.com/1498001/75573427-1b051e00-5a5d-11ea-8665-59bf23f21334.png)

**Comment by mycloudrevolution** [comment]
Hi,

might you please share the result of this snippet (VBR Server needs to be connected first)?

```
[Array]$RepoList = Get-VBRBackupRepository | Where-Object {$_.Type -ne "SanSnapshotOnly"} 
[Array]$ScaleOuts = Get-VBRBackupRepository -ScaleOut
if ($ScaleOuts) {
    foreach ($ScaleOut in $ScaleOuts) {
        $Extents = Get-VBRRepositoryExtent -Repository $ScaleOut
        foreach ($Extent in $Extents) {
            $RepoList = $RepoList + $Extent.repository
        }
    }
}
$RepoList | Select-Object Name, @{Name="CachedTotalSpaceGB"; Expression= {[Math]::Round([Decimal]$_.info.CachedTotalSpace/1GB,2)}}, @{Name="CachedFreeSpaceGB"; Expression= {[Math]::Round([Decimal]$_.info.CachedFreeSpace/1GB,2)}} | Format-Table -AutoSize
```

Special characters in jobs or repos often lead to this error.

**Comment by vMarkusK** [comment]
@antonin78  is there an update available?
