### ISSUE TITLE
VeeamBRStats - Fix Cloud Repo Space in v10

### ISSUE THREAD

**Issue by vMarkusK** [vMarkusK/Advanced-PRTG-Sensors#51]
`[Veeam.Backup.Core.CBackupRepository]::GetRepositoryBackupsSize($CloudRepos.Id.Guid)`

--> But this will break older versions (version check?)

**Comment by stylersnico** [comment]
Hi,

I have the same problem, maybe we can split the script in two powershell files for now?
I'm available if you want to do some tests.

**Comment by mycloudrevolution** [comment]
Duplicate of #52

**Comment by vMarkusK** [comment]
#57
