### ISSUE TITLE
VeeamBRStats Sensor not working after v10 upgrade

### ISSUE THREAD

**Issue by florian434** [vMarkusK/Advanced-PRTG-Sensors#52]
Hi,

I got a few Veeam sensors working fine with v9.5. After v10 upgrade I received the following error :
![image](https://user-images.githubusercontent.com/24958237/79988687-39145b00-84af-11ea-9944-1f1a7a17b931.png)

When I'm running the Script directly in Powershell, it seems to block on the following elements : 
![image](https://user-images.githubusercontent.com/24958237/79988855-6eb94400-84af-11ea-80e8-52e36b38e431.png)

I tried on different clients and always the same issue after v10 upgrade.

I'm using the lastest script available on Github.

**Comment by mycloudrevolution** [comment]
Thanks for reporting this. The root cause is a removed method in v10. 

Fix:
`[Veeam.Backup.Core.CBackupRepository]::GetRepositoryBackupsSize($CloudRepos.Id.Guid)`

Duplicate of #51

**Comment by mycloudrevolution** [comment]
Duplicate of #51

**Comment by vMarkusK** [comment]
#57
