### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by UAnton** [vMarkusK/Advanced-PRTG-Sensors#53]
Have a problem with the script.
Failed to connect to Veeam BR Host 'backup01.lan.local' with user 'Username'

P.S. Username - is a domain user but the script doesn't use domain like Domain_name\Usre_name

**Comment by mycloudrevolution** [comment]
How do you start the Script, via PS64.exe, or directly in PowerShell?

Have you tied to use the Veeam Console on the same server to verify the connection?

**Comment by UAnton** [comment]
Hi,
I start the script via PS64.exe.
Yes, I install Console and verify the connection.

**Comment by vMarkusK** [comment]
@UAnton is there an update available?

**Comment by cipo80** [comment]
Hi @vMarkusK I've a similar problem of @UAnton , If I execute the script by PowerShell Prompt in Veeam or PRTG both worked, but if I try by PowerShell Promp and PSx64, I received an authentication error:

`PS C:\Program Files (x86)\PRTG Network Monitor\Custom Sensors\EXEXML> .\PSx64.exe -f="PRTG-VeeamBRStats.ps1" -p="-BRHost srvveeam.xxxxx.it"
C:\Program Files (x86)\PRTG Network Monitor\Custom Sensors\EXEXML\PRTG-VeeamBRStats.ps1 : Failed to connect to Veeam
BR Host '-BRHost srvveeam.xxxxxx.it' with user 'administrator'
At line:1 char:1
+ &'C:\Program Files (x86)\PRTG Network Monitor\Custom Sensors\EXEXML\P ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,PRTG-VeeamBRStats.ps1`

**Comment by vMarkusK** [comment]
Passing Parameters to PSx64.exe is pretty tricks. In your case you can try these workarounds:

1. Just run `PRTG-VeeamBRStats.ps1 veeam01.lan.local`, or `.\PSx64.exe -f="PRTG-VeeamBRStats.ps1" -p="veeam01.lan.local"`
2. Modify the default for the BRHost  Parameter to your Veeam Server and do not add any parameters

**Comment by cipo80** [comment]
>     1. .\PSx64.exe -f="PRTG-VeeamBRStats.ps1" -p="veeam01.lan.local"

Very thank you @vMarkusK , in my case is working with `.\PSx64.exe -f="PRTG-VeeamBRStats.ps1" -p="veeam01.lan.local"` !

Great script/result, thank you for your work :)
