### ISSUE TITLE
VeeamBRStats stopped working after switching domain server -> workgroup Error PE095

### ISSUE THREAD

**Issue by Smooth1337** [vMarkusK/Advanced-PRTG-Sensors#56]
Hi,

I used to run the Veeam Server (Server 2012 R2) in same Domain as the PRTG Probe (Server 2019) and in that setup everything was working fine.

For some reasons I switched the Veeam Server out of the Domain into the Workgroup. 
Thats where the problems started. Now I always get the error PE095 (Access denied) in PRTG.

When I run the Script in the Powershell of the PRTG server (as the same local user that is provided in PRTG and on the Veeam Server) it is running successfully with the right results.
I'm also able to connect via the Veeam Backup & Replication 10 console to my non domain server (using the same credentials provided in PRTG).

Also other PRTG Sensors on that server are running fine.
I changed the $BRHost Value in the script to the Netbios name of the Veeam Server. But seems like this is making no difference.

Thanks for your support :)

**Comment by vMarkusK** [comment]
Have you tried to start a CMD Prompt with the local User and execute the Script together with PSx64.exe (like the sensor is working)?

**Comment by Smooth1337** [comment]
If I run it like you said as the same local user in a cmd on the PRTG Probe it is working. 
`C:\Program Files (x86)\PRTG Network Monitor\Custom Sensors\EXEXML>whoami
ts02\service_prtg

C:\Program Files (x86)\PRTG Network Monitor\Custom Sensors\EXEXML>PSx64.exe -f="PRTG-VeeamBRStats.ps1"
<prtg>
<result>
  <channel>Successful-Backups</channel>[...]
`

**Comment by Smooth1337** [comment]
I found the solution:
There used to stand the Hostname of the non domain computer (Veeam Server).
I removed it and leave it empty and voila -> working :)
![image](https://user-images.githubusercontent.com/67559259/86153243-a7a21480-bb01-11ea-90f7-6363f28f3db3.png)

**Comment by Smooth1337** [comment]
I found the solution:
I removed the Computername from the parent object (non domain Veeam Server) and now it is working.
![image](https://user-images.githubusercontent.com/67559259/86153468-05366100-bb02-11ea-8f50-1453ebe1d0a5.png)
