### ISSUE TITLE
Veeam reports

### ISSUE THREAD

**Issue by Gyslainh** [vMarkusK/Advanced-PRTG-Sensors#58]
Hi, PRTG keeps showing down for the sensor because the failed backup is at 1

So Simulation

Backup #1 : OK   PRTG will show ok
Backup #2 : Failure  PRTG will show down because the failure is at 1
Backup #3 : OK  PRTG will show down because the failure is at 0

How can i tell PRTG to update the status based on the last report?

Thanks

**Comment by vMarkusK** [comment]
Hi,

I am not sure if I understand the question.

Is the problem that the sensor is still showing error even if the backup jobs finally succeeded?

The sensor reports failed jobs within the last 24 h by default. You are not able to reset to green as long a job has failed within the configured time range.

**Comment by Gyslainh** [comment]
Ok and are we talking 24h as Midnight to midnight?




Gyslain Hamel
Administrateur de Système/System Administrator

[cid:image001.png@01D2BDDA.DCDB3780]

[cid:image003.png@01D5AE7A.E31E6200]<https://www.canadianbusiness.com/lists-and-rankings/growth-500/2019-information-technology-fastest-growing-companies/>

www.equipemicrofix.com<http://www.equipemicrofix.com/>
Bureau/Office: 514-394-0780
Sans-Frais/Toll-Free: 1-855-305-9939
Fax: 450-933-6229



[mcsa-windows-server-2016-certified-2020]<https://www.youracclaim.com/badges/ac59d77b-9209-48da-bf7a-dfadeaa187c3/public_url>

**Comment by vMarkusK** [comment]
The default Timeframe is (Script-execution-Time until (Script-execution-Time **-24h**) )
