### ISSUE TITLE
Monitor successful job after retry

### ISSUE THREAD

**Issue by Dijkstra173** [vMarkusK/Advanced-PRTG-Sensors#59]
Hello,

Some jobs are sometimes in status failed, but after a Veeam retry the job is successful. However the script still detects an error and increments the Failes-Backups channel which reports an error on the sensor on PRTG.

How to detect that a job is successful after a retry ?

Thank in advance

Regards,

**Comment by vMarkusK** [comment]
Hello @Dijkstra173 ,

the Script distinguishes between Failed and Failes.  Only if all Retries are failed the status Failed should occur. 

Can you confirm that for your environment?

**Comment by Dijkstra173** [comment]
Hello,

If the retry are successful the script still detects an error. I’ve made a few screenshots that may describe the problem better

I use Veeam Backup & replication v 10.0.0.4461 P1

Regards,

![2020-07-15 16_37_21-10 13 2 101 -Veeam01](https://user-images.githubusercontent.com/7527822/87559432-9557d700-c6ba-11ea-8634-a110e53b2958.png)
![2020-07-15 16_40_51-10 13 2 101 - Veeam02](https://user-images.githubusercontent.com/7527822/87559508-ad2f5b00-c6ba-11ea-8b4c-e2491944d7a2.png)
![2020-07-15 16_42_26-Sauvegarde Veeam03](https://user-images.githubusercontent.com/7527822/87559586-c801cf80-c6ba-11ea-8169-2d75c7fc0e21.png)

**Comment by vMarkusK** [comment]
I see the following state in you screenshot:

- Failed-Backuss - 0
- Failes-Backups - 1

If you don't want the sensor in error state if Failes occur, you need to reconfigure the PRTG Channel for "Failes-Backups". Per the Default a limit is active:

```
    $Count = $failsSessionsBk.Count
    Write-Output "<result>"
                "  <channel>Failes-Backups</channel>"
                "  <value>$Count</value>"
                "  <showChart>1</showChart>"
                "  <showTable>1</showTable>"
                "  <LimitMaxError>0</LimitMaxError>"
                "  <LimitMode>1</LimitMode>"
                "</result>"
```

**Comment by Dijkstra173** [comment]
I will modify these values, thank you very much for your help

**Comment by vMarkusK** [comment]
You're welcome.
