### ISSUE TITLE
Veeam BR 10 - ‘Disconnect-VBServer’ Not Recognized

### ISSUE THREAD

**Issue by Sebastien1807** [vMarkusK/Advanced-PRTG-Sensors#62]
Hi Markus,

First of all, thank you for making that script :-) I really look forward to be using it for my PRTG Monitor !

I followed all the procedure here : https://mycloudrevolution.com/de/2016/03/21/veeam-prtg-sensor-reloaded/ but I keep having an issue I can't seem to solve :S

On PRTG Program, I keep having that message :
_XML: The returned XML does not match the expected schema. (code: PE233) — JSON: The returned JSON does not match the expected structure (Invalid JSON.). (code: PE231)_

I made some research and I tested the Power Shell Script (v1.8) directly on my PRTG Server and the PowerShell Script Fail saying : 
_The term ‘Disconnect-VBRServer’ is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again._

I am running **Veeam Backup & Replication Version 10.0.0.4461** and I am running **PowerShell v5.1** both on my Veeam Server and PRTG Server and I am executing it from PSx64 just as said in the documentation you provided
OS Version for PRTG Server is : Windows Server 2019 1809 (Build 17763.379)
OS Version for Veeam Server is : Windows Server 2012 R2 6.3 (Build 9600)

I don’t really know where the problem can come from because it seems I can run Veeam PS Snapin without any problem on my Veeam Server (maybe because of the new snapin of the version 10?) 

Thank you for your help !

**Comment by vMarkusK** [comment]
Hi, hello,
Did you use the latest version from the Github Repo?
https://github.com/vMarkusK/Advanced-PRTG-Sensors/blob/master/Veeam/PRTG-VeeamBRStats.ps1

Sorry to ask, but the versioning of the script is broken... It's version 1.8 since a lot of changes... 

Might you please try to import the Veeam PS Snapin (in the VBR Server and the Probe) with the same user you have also tried to execute the script?
```
Add-PSSnapin -PassThru VeeamPSSnapIn
Connect-VBRServer -Server localhost #or your FQDN
```

**Comment by Sebastien1807** [comment]
Hi Markus, 

I changed my version of the script with the one you provided, but I still had the same error.
So I looked at the documentation of veeam and it says specifically : _You can run the Veeam PowerShell sessions from the Veeam backup server (locally) or **from a remote machine**. The remote machine must have the Veeam Backup & Replication Console installed._
(https://helpcenter.veeam.com/docs/backup/powershell/getting_started.html?ver=100)
So I decided to install it on my PRTG Server, and then use the command you provided : Add-PSSnapin -PassThru VeeamPSSnapIn 
Which worked fine.

Now the PowerShell script seems to go a bit further (launched from PRTG Server). But I have a new error when trying to use the script from my PRTG Server :
![image](https://user-images.githubusercontent.com/68741238/88550138-798cf300-d021-11ea-8c35-7e08958a723b.png)
It seems to not being able to join my Veeam Server with the user I am using (I am 100% sure that my credentials should be working)

So I decided to use the command line : _Connect-VBRServer -Server 'Veeam Server'_
And the following error appear
![image](https://user-images.githubusercontent.com/68741238/88550750-544cb480-d022-11ea-896c-4582423e764b.png)

I checked on Veeam Website and it says it's because of different version of the program between Veeam Server and the Remote Computer, which is strange because I have the same version of Veeam on both PRTG and Veeam
![image](https://user-images.githubusercontent.com/68741238/88551332-08e6d600-d023-11ea-873d-9b6fc26f055f.png)

Am I doing anything wrong? Didn't see anywhere I first needed to install the Veeam Backup & Replication on PRTG Server in the procedure to install the Sensor

**Comment by vMarkusK** [comment]
I think you just need to open the VBR Console on this server and connect to the VBR Server. The Console asks for an update. The PS Snap-In is included in this update.

**Comment by Sebastien1807** [comment]
Hi Markus,

OK nevermind :-) My bad, from my server-prtg I was running the Veeam Backup & Replication Console with localhost rather than my Veeam Server, so I never had the message to update. Now I had it and it's working :-) Thank you
