### ISSUE TITLE
XML Structural error after upgrade to 10.0.1.4854

### ISSUE THREAD

**Issue by cipo80** [vMarkusK/Advanced-PRTG-Sensors#63]
Hello Markus,

the script working very good until the previously version, after upgrade to the last one build 10.0.1.4854 I get this error:

**XML: Structural error in xml file, 3 open items. -- JSON: The returned JSON does not match the expected structure (Invalid JSON.). (code: PE231)** 

I use the script with PS64, these are the PRTG parameters: **.\PSx64.exe -f="PRTG-VeeamBRStats.ps1" -p="veeamhostname"**

Thank you for this great script!

**Comment by vMarkusK** [comment]
Hi @cipo80 ,

have you upgraded the Veeam Console on the PRTG Probe after the Veeam Backup & Replication Upgrade?

**Comment by cipo80** [comment]
> 
> 
> Hi @cipo80 ,
> 
> have you upgraded the Veeam Console on the PRTG Probe after the Veeam Backup & Replication Upgrade?

Hi @vMarkusK , I've upgrade the console and now it's working, thank you for the suggestion!
