### ISSUE TITLE
Exception calling "SyncSpaceInfoToDb" with "2" argument(s)

### ISSUE THREAD

**Issue by martinorob** [vMarkusK/Advanced-PRTG-Sensors#65]
Veeam Version 10.0.1.4854

Get-vPCRepoInfo : Exception calling "SyncSpaceInfoToDb" with "2" argument(s): "[IP address] Failed to connect to
Installer service."
At C:\Program Files (x86)\PRTG Network Monitor\Custom Sensors\EXEXML\PRTG-VeeamBRStats.ps1:516 char:35
+ ForEach ($RawRepo in ($repoList | Get-vPCRepoInfo)){
+                                   ~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-vPCRepoInfo

Get-vPCRepoInfo : at Get-vPCRepoInfo<Process>, C:\Program Files (x86)\PRTG Network Monitor\Custom
Sensors\EXEXML\PRTG-VeeamBRStats.ps1: line 156
at <ScriptBlock>, C:\Program Files (x86)\PRTG Network Monitor\Custom Sensors\EXEXML\PRTG-VeeamBRStats.ps1: line 516
at <ScriptBlock>, <No file>: line 1
At C:\Program Files (x86)\PRTG Network Monitor\Custom Sensors\EXEXML\PRTG-VeeamBRStats.ps1:516 char:35
+ ForEach ($RawRepo in ($repoList | Get-vPCRepoInfo)){
+                                   ~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-vPCRepoInfo

This broke my PRTG Sensor with 
XML: Structural error in xml file, 4 open items. -- JSON: The returned JSON does not match the expected structure (Invalid JSON.). (code: PE231)

**Comment by vMarkusK** [comment]
Hi @martinorob ,

do you use the latest version of the script from the GitHub Repo?

Do you use any special Repositories (Cloud Connect and so on)?

**Comment by martinorob** [comment]
yes, Last version and no Cloud Connect.. 🙁 

`Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): A
DEBUG: Veeam.Backup.Model.CBackupRepositoryInfo

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): Y
DEBUG: SyncSpaceInfoToDb Failed

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): A
Get-vPCRepoInfo : Exception calling "SyncSpaceInfoToDb" with "2" argument(s): "[10.8.1.101] Failed to connect to
Installer service."
At C:\Users\Administrator\Desktop\PRTG-VeeamBRStats.ps1:516 char:35
+ ForEach ($RawRepo in ($repoList | Get-vPCRepoInfo)){
+                                   ~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-vPCRepoInfo

Get-vPCRepoInfo : at Get-vPCRepoInfo<Process>, C:\Users\Administrator\Desktop\PRTG-VeeamBRStats.ps1: line 156
at <ScriptBlock>, C:\Users\Administrator\Desktop\PRTG-VeeamBRStats.ps1: line 516
at <ScriptBlock>, <No file>: line 1
At C:\Users\Administrator\Desktop\PRTG-VeeamBRStats.ps1:516 char:35
+ ForEach ($RawRepo in ($repoList | Get-vPCRepoInfo)){
+                                   ~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-vPCRepoInfo

DEBUG: Veeam.Backup.Model.CBackupRepositoryInfo
`

**Comment by vMarkusK** [comment]
Which Repo type is located on 10.8.1.101?
Are there maybe any firewall blocks between the probe one this ip?
