### ISSUE TITLE
Managed Agent Jobs not covered

### ISSUE THREAD

**Issue by DaStanka** [vMarkusK/Advanced-PRTG-Sensors#67]
Agent jobs are not recognized.
As already reported on Markus' homepage.

"Get-VBREPJob" gives no result.

Answer from Markus:
Ich werde mir das mal näher anschauen und bescheid geben.

**Comment by vMarkusK** [comment]
@DaStanka  might you please verify #102 ?

**Comment by DaStanka** [comment]
Hi Markus,

Agent jobs are now recognized.
It works.

Thank you!!
