### ISSUE TITLE
Script stop working after win.update

### ISSUE THREAD

**Issue by cipo80** [vMarkusK/Advanced-PRTG-Sensors#70]
Hi Markus,

your great script (always many thanks for your work) stop working last Friday, 18 December 2020, on our environment with a time out error: "Your request has timed out. Depending...etc"
I haven't update or modify anythings, only windows update occur the day before.
If I try to execute in the probe by PS, the script working good:

PS C:\Program Files (x86)\PRTG Network Monitor\Custom Sensors\EXEXML> .\PSx64.exe -f="PRTG-VeeamBRStats.ps1" -p="srvveeam.xxxxxx.it"
<prtg>
<result>
  <channel>Successful-Backups</channel>
  <value>3</value>
  <showChart>1</showChart>
  <showTable>1</showTable>
</result>

etc...

I've activate the log, but i don't understand where is the error.
Any idea?

Thank you and merry Chrstmas!

Data['linuxloginpassword'].asString := '***';
Data['notonpod'].asString := '0';
Data['fastcount'].asString := '0';
Data['lastmsg'].asString := '#O18';
Data['resultfile'].asString := 'Result of Sensor 5421.txt';
Data['windowsloginusername'].asString := 'administrator';
Data['hostv6'].asString := '';
Data['exefile'].asString := 'PSx64.exe';
Data['lastuptime'].asString := '0';
Data['writeresult'].asString := '1';
Data['blockedsens'].asString := '';
Data['reqmsginterval'].asString := '14400';
Data['windowslogindomain'].asString := 'xxxxxx.it';
Data['tlsexplicit_imap'].asString := '';
Data['channelnames'].asString := 'Successful-Backups'#$D#$A + 
'2'#$D#$A + 
'Warning-Backups'#$D#$A + 
'3'#$D#$A + 
'Failes-Backups'#$D#$A + 
'4'#$D#$A + 
'Failed-Backups'#$D#$A + 
'5'#$D#$A + 
'Running-Backups'#$D#$A + 
'6'#$D#$A + 
'TotalBackupRead'#$D#$A + 
'7'#$D#$A + 
'TotalBackupTransfer'#$D#$A + 
'8'#$D#$A + 
'Successful-BackupCopys'#$D#$A + 
'9'#$D#$A + 
'Warning-BackupCopys'#$D#$A + 
'10'#$D#$A + 
'Failes-BackupCopys'#$D#$A + 
'11'#$D#$A + 
'Failed-BackupCopys'#$D#$A + 
'12'#$D#$A + 
'Running-BackupCopys'#$D#$A + 
'13'#$D#$A + 
'Idle-BackupCopys'#$D#$A + 
'14'#$D#$A + 
'Successful-Replications'#$D#$A + 
'15'#$D#$A + 
'Warning-Replications'#$D#$A + 
'16'#$D#$A + 
'Failes-Replications'#$D#$A + 
'17'#$D#$A + 
'Failed-Replications'#$D#$A + 
'18'#$D#$A + 
'Running-Replications'#$D#$A + 
'19'#$D#$A + 
'Successful-Endpoints'#$D#$A + 
'20'#$D#$A + 
'Warning-Endpoints'#$D#$A + 
'21'#$D#$A + 
'Failes-Endpoints'#$D#$A + 
'22'#$D#$A + 
'Running-Endpoints'#$D#$A + 
'23'#$D#$A + 
'REPO - Repo_V2-1'#$D#$A + 
'24'#$D#$A + 
'REPO - Repo_V1-1'#$D#$A + 
'25'#$D#$A + 
'';
Data['tlsexplicit_default'].asString := '';
Data['canlinux'].asString := '0';
Data['isexesensor'].asString := '1';
Data['windowsloginpassword'].asString := '***';
Data['environment'].asString := '';
Data['mutexname'].asString := '';
Data['channelinfos'].asString := '{"2":{"Unit":"oukCustom","CustomUnit":"#","ValueLookupName":"","LimitMode":"0","LimitMinError":"","LimitMinWarning":"","LimitMaxError":"","LimitMaxWarning":""},"3":{"Unit":"oukCustom","CustomUnit":"#","ValueLookupName":"","LimitMode":"1","LimitMinError":"","LimitMinWarning":"","LimitMaxError":"","LimitMaxWarning":"0"},"4":{"Unit":"oukCustom","CustomUnit":"#","ValueLookupName":"","LimitMode":"1","LimitMinError":"","LimitMinWarning":"","LimitMaxError":"","LimitMaxWarning":"2"},"5":{"Unit":"oukCustom","CustomUnit":"#","ValueLookupName":"","LimitMode":"1","LimitMinError":"","LimitMinWarning":"","LimitMaxError":"0","LimitMaxWarning":""},"6":{"Unit":"oukCustom","CustomUnit":"#","ValueLookupName":"","LimitMode":"0","LimitMinError":"","LimitMinWarning":"","LimitMaxError":"","LimitMaxWarning":""},"7":{"Unit":"oukCustom","CustomUnit":"GB","ValueLookupName":"","LimitMode":"0","LimitMinError":"","LimitMinWarning":"","LimitMaxError":"","LimitMaxWarning":""},"8":{"Unit":"oukCustom","CustomUnit":"GB","ValueLookupName":"","LimitMode":"0","LimitMinError":"","LimitMinWarning":"","LimitMaxError":"","LimitMaxWarning":""},"9":{"Unit":"oukCustom","CustomUnit":"#","ValueLookupName":"","LimitMode":"0","LimitMinError":"","LimitMinWarning":"","LimitMaxError":"","LimitMaxWarning":""},"10":{"Unit":"oukCustom","CustomUnit":"#","ValueLookupName":"","LimitMode":"1","LimitMinError":"","LimitMinWarning":"","LimitMaxError":"","LimitMaxWarning":"0"},"11":{"Unit":"oukCustom","CustomUnit":"#","ValueLookupName":"","LimitMode":"1","LimitMinError":"","LimitMinWarning":"","LimitMaxError":"","LimitMaxWarning":"4"},"12":{"Unit":"oukCustom","CustomUnit":"#","ValueLookupName":"","LimitMode":"1","LimitMinError":"","LimitMinWarning":"","LimitMaxError":"0","LimitMaxWarning":""},"13":{"Unit":"oukCustom","CustomUnit":"#","ValueLookupName":"","LimitMode":"0","LimitMinError":"","LimitMinWarning":"","LimitMaxError":"","LimitMaxWarning":""},"14":{"Unit":"oukCustom","CustomUnit":"#","ValueLookupName":"","LimitMode":"0","LimitMinError":"","LimitMinWarning":"","LimitMaxError":"","LimitMaxWarning":""},"15":{"Unit":"oukCustom","CustomUnit":"#","ValueLookupName":"","LimitMode":"0","LimitMinError":"","LimitMinWarning":"","LimitMaxError":"","LimitMaxWarning":""},"16":{"Unit":"oukCustom","CustomUnit":"#","ValueLookupName":"","LimitMode":"1","LimitMinError":"","LimitMinWarning":"","LimitMaxError":"","LimitMaxWarning":"0"},"17":{"Unit":"oukCustom","CustomUnit":"#","ValueLookupName":"","LimitMode":"1","LimitMinError":"","LimitMinWarning":"","LimitMaxError":"0","LimitMaxWarning":""},"18":{"Unit":"oukCustom","CustomUnit":"#","ValueLookupName":"","LimitMode":"1","LimitMinError":"","LimitMinWarning":"","LimitMaxError":"0","LimitMaxWarning":""},"19":{"Unit":"oukCustom","CustomUnit":"#","ValueLookupName":"","LimitMode":"0","LimitMinError":"","LimitMinWarning":"","LimitMaxError":"","LimitMaxWarning":""},"20":{"Unit":"oukCustom","CustomUnit":"#","ValueLookupName":"","LimitMode":"0","LimitMinError":"","LimitMinWarning":"","LimitMaxError":"","LimitMaxWarning":""},"21":{"Unit":"oukCustom","CustomUnit":"#","ValueLookupName":"","LimitMode":"1","LimitMinError":"","LimitMinWarning":"","LimitMaxError":"","LimitMaxWarning":"0"},"22":{"Unit":"oukCustom","CustomUnit":"#","ValueLookupName":"","LimitMode":"1","LimitMinError":"","LimitMinWarning":"","LimitMaxError":"0","LimitMaxWarning":""},"23":{"Unit":"oukCustom","CustomUnit":"#","ValueLookupName":"","LimitMode":"0","LimitMinError":"","LimitMinWarning":"","LimitMaxError":"","LimitMaxWarning":""},"24":{"Unit":"oukPercent","CustomUnit":"#","ValueLookupName":"","LimitMode":"1","LimitMinError":"10","LimitMinWarning":"12","LimitMaxError":"","LimitMaxWarning":""},"25":{"Unit":"oukPercent","CustomUnit":"#","ValueLookupName":"","LimitMode":"1","LimitMinError":"4","LimitMinWarning":"7","LimitMaxError":"","LimitMaxWarning":""}}';
Data['uptimecount'].asString := '0';
Data['reboot'].asString := '44187.5029318981';
Data['usednstime'].asString := '0';
Data['linuxlogindomain'].asString := '';
Data['tlsexplicit_port'].asString := '';
Data['monitorchange'].asString := '';
Data['inerror'].asString := '1';
Data['sensorid'].asString := '5421';
Data['ipversion'].asString := '0';
Data['tlsexplicit_smtp'].asString := '';
Data['host'].asString := 'srvveeam.xxxxxx.it';
Data['usewindowsauthentication'].asString := '1';
Data['simulate'].asString := '0';
Data['tlsexplicit_ftp'].asString := '';
Data['timeout'].asString := '60';
Data['exeparams'].asString := '.\PSx64.exe -f="PRTG-VeeamBRStats.ps1" -p="srvveeam.xxxxxx.it"';
Data['momopersistent'].asString := '';
Data['tlsexplicit_pop3'].asString := '';

Any Idea?

**Comment by vMarkusK** [comment]
Hi @cipo80 ,

Sorry I haven't seen this issue before.

Which OS do you use for the probe? 
So other sensors still work on that probe? 
Do you have a list of the installed updates? 


Best wishes and merry Christmas 
Markus

**Comment by cipo80** [comment]
Hi @vMarkusK , thank you for the reply.

The probe are Windows 2019, the veeam server are Windows 2016.
All other sensors and PS script are working good.
The last windows update on probe are KB4592440.

Best wishes to you!!

**Comment by vMarkusK** [comment]
As KB4592440 is a huge Cumulative update I don't see a chance to identify the root cause based on the release notes of the patch.

Do the other PS based sensors also use PSx64.exe?

Have you tried to increase the timeout of the the sensor (up to 900 seconds are possible) ?

**Comment by cipo80** [comment]
Hi @vMarkusK and Happy new year! 
I'm back to work today, I've increase the timeout and it's working again ;)
I didn't notice before the parameter on the sensor, may bey after the update psx64.exe is slowed down or counterparty Veeam server give the result a little bit late.

Anyway thank you again for the support!

Have a good year , I hope for all!

Anyway thank you
