### ISSUE TITLE
Problem with VB&R v10

### ISSUE THREAD

**Issue by dancesa** [vMarkusK/Advanced-PRTG-Sensors#71]
Hi Markus,

after we update VB&R v9.5 to v10, the PRTG Sensor return this error:
"XML: Structural error in xml file, 3 open items. -- JSON: The returned JSON does not match the expected structure (Invalid JSON.). (code: PE231)"
![2021-01-12 14_35_13-Window](https://user-images.githubusercontent.com/71828602/104321151-87f19d00-54e3-11eb-8deb-0bd649d83944.png)

do you have any solutions ?

Thanks.

Best regards.

Daniele.

**Comment by vMarkusK** [comment]
Hi,

I have a few questions:

- do you use the latest version from the Repo?
- have you changed anything else than the Veeam upgrade?
- have you also upgraded all veaam consoles (especial prtg probe)?
- do you use special characters in Repo names?
- have you tried to execute the script outside of PRTG?

Best wishes
Markus

**Comment by JamesW-AU** [comment]
I've got the exact same problem. Using the latest code from the repo, Veeam B&R server and console installed on PRTG server are the same version, no special characters in any names of anything in Veeam, and if I run the script manually it seems to be fine:

PS C:\Program Files (x86)\PRTG Network Monitor\Custom Sensors\EXEXML> .\PSx64.exe -f="PLC PRTG-VeeamBRStats.ps1"
0:\Program Files (x86)\PRTG Network Monitor\Custom Sensors\EXEXML\PLC PRTG-VeeamBRStats.ps1
PS C:\Program Files (x86)\PRTG Network Monitor\Custom Sensors\EXEXML>

**Comment by dancesa** [comment]
Hi to all,

after update PRTG, the problem is resolved.

Thanks to all.

Best regards.

Daniele.
