### ISSUE TITLE
v11 GA Compatibility

### ISSUE THREAD

**Issue by vMarkusK** [vMarkusK/Advanced-PRTG-Sensors#75]

**Comment by adblocker-1** [comment]
Delete:
ROW: 42
#region: Start Load VEEAM Snapin (if not already loaded)
if (!(Get-PSSnapin -Name VeeamPSSnapIn -ErrorAction SilentlyContinue)) {
	if (!(Add-PSSnapin -PassThru VeeamPSSnapIn)) {
		# Error out if loading fails
		Write-Error "`nERROR: Cannot load the VEEAM Snapin."
		Exit
	}
}
#endregion

Change:
ROW: 52
#region: Functions
Function **Get-vPCRepoInfo** {
[CmdletBinding()]

to: 
#region: Functions
Function **Get-VBRBackupRepository**  {
[CmdletBinding()]

Failed Backups will show again, no **Repo** report you need to add the sensor again to PRTG

**Comment by vMarkusK** [comment]
@adblocker-1 Thanks for your feedback.

Might you please explain that in a bit more detail?
> Failed Backups will show again, no Repo report you need to add the sensor again to PRTG

Why should the function be renamed?

Why should loading of the Snapin be removed?

Have you seen the changes made in #76 ?
