### ISSUE TITLE
Your request has timed out

### ISSUE THREAD

**Issue by dancesa** [vMarkusK/Advanced-PRTG-Sensors#82]
Hi support, my sensor in PRTG not working from a different days. Returned this error:
![2021-04-19 09_50_06-Window](https://user-images.githubusercontent.com/71828602/115201189-52b5a600-a0f5-11eb-94c0-66fa75afc93c.png)

If I try from the probe by running the ps, it works
![image](https://user-images.githubusercontent.com/71828602/115201862-10d92f80-a0f6-11eb-88e7-71985cd7a7b1.png)

Do you have any idea what that might be?

Thanks a lot.

Best regards.

Daniele.

**Comment by vMarkusK** [comment]
You are able to increase the timeout of the sensor in PRTG. This should help.

**Comment by dancesa** [comment]
Hi Markus,
it’s works!!
Thanks a lot. 😊

Bets regards.


***@***.***D73505.D61BE560]
Daniele Cesario
Sistemista

______________________
SAIDEA srl | Via Kufstein, 5 - loc. Spini 38121 - Trento (TN)
tel 0461-245589 fax 0461-243884 | www.saidea.it<http://www.saidea.it>


AVVISO DI RISERVATEZZA
Con questo avviso, si precisa che il testo e gli eventuali documenti trasmessi in questo messaggio contengono informazioni riservate al destinatario indicato. Se si ritiene di non essere il destinatario  di questa e-mail, o se si è ricevuto questa e-mail per errore, si prega di darne comunicazione al mittente  e di provvedere immediatamente alla sua distruzione. Grazie.


Da: Markus Kraus ***@***.***>
Inviato: lunedì 19 aprile 2021 10:11
A: vMarkusK/Advanced-PRTG-Sensors ***@***.***>
Cc: Daniele Cesario, SAIDEA srl ***@***.***>; Author ***@***.***>
Oggetto: Re: [vMarkusK/Advanced-PRTG-Sensors] Your request has timed out (#82)


You are able to increase the timeout of the sensor in PRTG. This should help.
