### ISSUE TITLE
XML: Structural error in xml file, 12 open items. -- JSON: The returned JSON does not match the expected structure (Invalid JSON.). (code: PE231)

### ISSUE THREAD

**Issue by andriesgithub** [vMarkusK/Advanced-PRTG-Sensors#89]
Hi, 

Our sensor has stopped working for a few days now. In the output we see the following error: 

**### Get-vPCRepoInfo : Exception calling "SyncSpaceInfoToDb" with "2" argument(s): " 
Failed to register new route" 
At C:\Program Files (x86)\PRTG Network Monitor\custom sensors \EXEXML\PRTG-Veeam 
BRStats.ps1:635 char:29** 

What could this be? Nothing wrong with the sensor has changed.

**Comment by vMarkusK** [comment]
Hi,
the "Get-vPCRepoInfo" function precesses all Datastores in your Veeam Inventory.

Had something changed in your Veeam Environment (new or changed Repo, etc.)?
Do you use the latest version of the Script from this Repo?
Which Veeam Version do you use?

Might you please run the Script with the -debug switch and share the result?
