### ISSUE TITLE
SyncSpaceInfoToDb Failed -->  $RepoData = $repoList | Get-vPCRepoInfo

### ISSUE THREAD

**Issue by carsten0407** [vMarkusK/Advanced-PRTG-Sensors#92]
Hi Guys,

suddenly, I have the following error with at the following command:

 **$RepoData = $repoList | Get-vPCRepoInfo**

<result>
  <channel>Failes-Endpoints</channel>
  <value>0</value>
  <showChart>1</showChart>
  <showTable>1</showTable>
  <LimitMaxError>0</LimitMaxError>
  <LimitMode>1</LimitMode>
</result>
<result>
  <channel>Running-Endpoints</channel>
  <value>0</value>
  <showChart>1</showChart>
  <showTable>1</showTable>
</result>
DEBUG: SyncSpaceInfoToDb Failed
Get-vPCRepoInfo : Ausnahme beim Aufrufen von "SyncSpaceInfoToDb" mit 2 Argument(en):  "Failed to register new route"
In C:\Program Files (x86)\PRTG Network Monitor\Custom Sensors\EXEXML\PRTG-VeeamBRStatsLocalBackupV3.0.ps1:624 Zeichen:29
+     $RepoData = $repoList | Get-vPCRepoInfo
+                             ~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-vPCRepoInfo
 
Get-vPCRepoInfo : bei Get-vPCRepoInfo<Process>, C:\Program Files (x86)\PRTG Network Monitor\Custom 
Sensors\EXEXML\PRTG-VeeamBRStatsLocalBackupV3.0.ps1: Zeile 197
bei <ScriptBlock>, C:\Program Files (x86)\PRTG Network Monitor\Custom 
Sensors\EXEXML\PRTG-VeeamBRStatsLocalBackupV3.0.ps1: Zeile 624
bei <ScriptBlock>, <Keine Datei>: Zeile 1
In C:\Program Files (x86)\PRTG Network Monitor\Custom Sensors\EXEXML\PRTG-VeeamBRStatsLocalBackupV3.0.ps1:624 Zeichen:29
+     $RepoData = $repoList | Get-vPCRepoInfo
+                             ~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-vPCRepoInfo
 
DEBUG: Veeam.Backup.Model.CBackupRepositoryInfo
DEBUG: SyncSpaceInfoToDb Failed
Get-vPCRepoInfo : Ausnahme beim Aufrufen von "SyncSpaceInfoToDb" mit 2 Argument(en):  "Failed to register new route"
In C:\Program Files (x86)\PRTG Network Monitor\Custom Sensors\EXEXML\PRTG-VeeamBRStatsLocalBackupV3.0.ps1:624 Zeichen:29
+     $RepoData = $repoList | Get-vPCRepoInfo
+                             ~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-vPCRepoInfo
 
Get-vPCRepoInfo : bei Get-vPCRepoInfo<Process>, C:\Program Files (x86)\PRTG Network Monitor\Custom 
Sensors\EXEXML\PRTG-VeeamBRStatsLocalBackupV3.0.ps1: Zeile 197
bei <ScriptBlock>, C:\Program Files (x86)\PRTG Network Monitor\Custom 
Sensors\EXEXML\PRTG-VeeamBRStatsLocalBackupV3.0.ps1: Zeile 624
bei <ScriptBlock>, <Keine Datei>: Zeile 1
In C:\Program Files (x86)\PRTG Network Monitor\Custom Sensors\EXEXML\PRTG-VeeamBRStatsLocalBackupV3.0.ps1:624 Zeichen:29
+     $RepoData = $repoList | Get-vPCRepoInfo
+                             ~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-vPCRepoInfo
 
DEBUG: Veeam.Backup.Model.CBackupRepositoryInfo
DEBUG: SyncSpaceInfoToDb Failed
Get-vPCRepoInfo : Ausnahme beim Aufrufen von "SyncSpaceInfoToDb" mit 2 Argument(en):  "Failed to register new route"
In C:\Program Files (x86)\PRTG Network Monitor\Custom Sensors\EXEXML\PRTG-VeeamBRStatsLocalBackupV3.0.ps1:624 Zeichen:29
+     $RepoData = $repoList | Get-vPCRepoInfo
+                             ~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-vPCRepoInfo
 
Get-vPCRepoInfo : bei Get-vPCRepoInfo<Process>, C:\Program Files (x86)\PRTG Network Monitor\Custom 
Sensors\EXEXML\PRTG-VeeamBRStatsLocalBackupV3.0.ps1: Zeile 197
bei <ScriptBlock>, C:\Program Files (x86)\PRTG Network Monitor\Custom 
Sensors\EXEXML\PRTG-VeeamBRStatsLocalBackupV3.0.ps1: Zeile 624
bei <ScriptBlock>, <Keine Datei>: Zeile 1
In C:\Program Files (x86)\PRTG Network Monitor\Custom Sensors\EXEXML\PRTG-VeeamBRStatsLocalBackupV3.0.ps1:624 Zeichen:29
+     $RepoData = $repoList | Get-vPCRepoInfo
+                             ~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-vPCRepoInfo
 
DEBUG: Veeam.Backup.Model.CBackupRepositoryInfo
<result>
  <channel>REPO - Default Backup Repository - BACKUP01</channel>
  <value>59</value>
  <unit>Percent</unit>
  <showChart>1</showChart>
  <showTable>1</showTable>
  <LimitMinWarning>20</LimitMinWarning>
  <LimitMinError>10</LimitMinError>
  <LimitMode>1</LimitMode>
</result>
<result>
  <channel>REPO - Backup Repository - B2D NAS01</channel>
  <value>67</value>
  <unit>Percent</unit>
  <showChart>1</showChart>
  <showTable>1</showTable>
  <LimitMinWarning>20</LimitMinWarning>
  <LimitMinError>10</LimitMinError>
  <LimitMode>1</LimitMode>
</result>
<result>
  <channel>REPO - Backup Repository - WAN Acceleration</channel>
  <value>63</value>
  <unit>Percent</unit>
  <showChart>1</showChart>
  <showTable>1</showTable>
  <LimitMinWarning>20</LimitMinWarning>
  <LimitMinError>10</LimitMinError>
  <LimitMode>1</LimitMode>
</result>
</prtg>

**Comment by carsten0407** [comment]
Same result with the PRTG-VeeamBRStats-v3.ps1

PS C:\Program Files (x86)\PRTG Network Monitor\Custom Sensors\EXEXML> .\PRTG-VeeamBRStats-v3.ps1 -BRHost LOCALHOST
C:\Program Files (x86)\PRTG Network Monitor\Custom Sensors\EXEXML\PRTG-VeeamBRStats-v3.ps1 : Ausnahme beim Aufrufen von 
"SyncSpaceInfoToDb" mit 2 Argument(en):  "Failed to register new route"
In Zeile:1 Zeichen:1
+ .\PRTG-VeeamBRStats-v3.ps1 -BRHost LOCALHOST
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,PRTG-VeeamBRStats-v3.ps1

**Comment by carsten0407** [comment]
PS C:\Program Files (x86)\PRTG Network Monitor\Custom Sensors\EXEXML> .\PRTG-VeeamBRStats-v3.ps1 -BRHost LOCALHOST -Debug
DEBUG: Starting to Process Connection to 'LOCALHOST' with user 'serviceuser' ...
DEBUG: Connecting BRHost 'LOCALHOST' with user 'kmserviceuser'...
DEBUG: SyncSpaceInfoToDb Failed
C:\Program Files (x86)\PRTG Network Monitor\Custom Sensors\EXEXML\PRTG-VeeamBRStats-v3.ps1 : Ausnahme beim Aufrufen von 
"SyncSpaceInfoToDb" mit 2 Argument(en):  "Failed to register new route"
In Zeile:1 Zeichen:1
+ .\PRTG-VeeamBRStats-v3.ps1 -BRHost LOCALHOST -Debug
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,PRTG-VeeamBRStats-v3.ps1

**Comment by vMarkusK** [comment]
Hi @carsten0407 ,

Which VBR Version do you use and what types of repos have you configured?

**Comment by carsten0407** [comment]
We use the  11.0.1.1261
Two smb Shares and one local store

But wait, we found another mistake maybe.
That is the message also from the ps1


***@***.***


Mit freundlichen Grüßen / best regards

i. A. Carsten Trautmann

Senior System Engineer
Operation Center
IT-Service
[http://support.it.konicaminolta.de/signatures/KM_LOGO.jpg]
Konica Minolta Business Solutions Deutschland GmbH
Mittlerer Pfad 1, 70499 Stuttgart, Germany
Phone:
+49 (711) 1385 - 131<tel:+497111385131>
Fax:
+49 (711) 1385 - 222
Mail:
***@***.******@***.***>
Web:
www.konicaminolta.de<http://www.konicaminolta.de>
District Court / Amtsgericht: Hannover, HRB 61209
Management / Geschäftsführer:
Joerg Hartmann & Kenichiro Fukasawa
Aufsichtsratsvorsitzender: Jens Venrath
Informationen über die Verarbeitung Ihrer personenbezogenen Daten durch uns können Sie unter https://www.konicaminolta.de/de/business-solutions/meta/dseg.html einsehen.

[http://support.it.konicaminolta.de/signatures/emailPrinzip.jpg]

Von: Markus Kraus ***@***.***>
Gesendet: Mittwoch, 13. April 2022 14:53
An: vMarkusK/Advanced-PRTG-Sensors ***@***.***>
Cc: Trautmann, Carsten ***@***.***>; Mention ***@***.***>
Betreff: Re: [vMarkusK/Advanced-PRTG-Sensors] SyncSpaceInfoToDb Failed --> $RepoData = $repoList | Get-vPCRepoInfo (Issue #92)


[EXTERNAL E-MAIL] Use caution when following links or opening attachments.

Hi @carsten0407<https://github.com/carsten0407> ,

Which VBR Version do you use and what types of repos have you configured?

**Comment by carsten0407** [comment]
We fix it, was a problem on veeam site


Mit freundlichen Grüßen / best regards

i. A. Carsten Trautmann

Senior System Engineer
Operation Center
IT-Service
[http://support.it.konicaminolta.de/signatures/KM_LOGO.jpg]
Konica Minolta Business Solutions Deutschland GmbH
Mittlerer Pfad 1, 70499 Stuttgart, Germany
Phone:
+49 (711) 1385 - 131<tel:+497111385131>
Fax:
+49 (711) 1385 - 222
Mail:
***@***.******@***.***>
Web:
www.konicaminolta.de<http://www.konicaminolta.de>
District Court / Amtsgericht: Hannover, HRB 61209
Management / Geschäftsführer:
Joerg Hartmann & Kenichiro Fukasawa
Aufsichtsratsvorsitzender: Jens Venrath
Informationen über die Verarbeitung Ihrer personenbezogenen Daten durch uns können Sie unter https://www.konicaminolta.de/de/business-solutions/meta/dseg.html einsehen.

[http://support.it.konicaminolta.de/signatures/emailPrinzip.jpg]

Von: Markus Kraus ***@***.***>
Gesendet: Mittwoch, 13. April 2022 14:53
An: vMarkusK/Advanced-PRTG-Sensors ***@***.***>
Cc: Trautmann, Carsten ***@***.***>; Mention ***@***.***>
Betreff: Re: [vMarkusK/Advanced-PRTG-Sensors] SyncSpaceInfoToDb Failed --> $RepoData = $repoList | Get-vPCRepoInfo (Issue #92)


[EXTERNAL E-MAIL] Use caution when following links or opening attachments.

Hi @carsten0407<https://github.com/carsten0407> ,

Which VBR Version do you use and what types of repos have you configured?
