### ISSUE TITLE
Backup Copy Jobs now recognized

### ISSUE THREAD

**Issue by cerri** [vMarkusK/Advanced-PRTG-Sensors#93]
Hello,

the sensor cannot recognize a Copy Job.
I'm running the script directly on the Veeam Server with HTTP Push Data sensor type.
On this server there are:
2 Backup Jobs
1 Backup Copy Job

But I cannot see any Copy Job result.
Is it an issue or I am missing something?

Thank you

<img width="671" alt="Schermata 2022-07-14 alle 15 16 16" src="https://user-images.githubusercontent.com/3293599/178992006-af3a88fd-fcb8-4a8e-8344-baee113418e9.png">
<img width="1267" alt="Schermata 2022-07-14 alle 15 18 21" src="https://user-images.githubusercontent.com/3293599/178992009-153c63d6-d34a-4fe6-92d0-c80ea206bedc.png">
<img width="1294" alt="Schermata 2022-07-14 alle 15 18 28" src="https://user-images.githubusercontent.com/3293599/178992015-c3a73eb6-d3f9-4436-8d5f-5a7715242680.png">

**Comment by vMarkusK** [comment]
Hi @cerri ,

Do you use the -selChann parameter to change scope of the script?

Which VBR version do you use?

Might you please run the script run with -Debug switch and share the output?

I will also have a look at that in my lab.

Best wishes
Markus

**Comment by OashaP** [comment]
Hello @Markus,

I hope it's okay to revive this rather old thread.
I have the same error as Cerri: Unfortunately our backup copy jobs are not displayed in PRTG.

To cover your previous points:
- No, we didn't change anything in the -selChann parameter (or anything similar to change the scope).
- we are on the latest version v12.0.0.1420
- The output with the -Debug switch looks exactly like it is in PRTG: 0 Backup Copy Success, 0 Backup Copy Failed, 0 Backup Copy Idle, etc. ...

I thank you for your help in advance.

Best regards

OashaP

**Comment by vMarkusK** [comment]
Hello @OashaP ,

was it working at any time for you?
What is the schedule frequency of your Copy Jobs?

This snippet will return all Copy Job-Runs within the last month, might you please verify the output:
```
$HourstoCheck = 720
$allSesh = Get-VBRBackupSession  
$seshListBkc = @($allSesh | Where-Object{($_.CreationTime -ge (Get-Date).AddHours(-$HourstoCheck)) -and $_.JobType -eq "BackupSync"})  
$seshListBkc
```

**Comment by OashaP** [comment]
Hello Markus,

firstly, thank you for helping us with this one.
Regarding your points:
- Everything else was working as expected, but backup copy never did
- Mostly daily
- The output of that command is empty. I run this command inside the Veeam PowerShell and just receive the Command Prompt back to start the next query

Best regards
OashaP

**Comment by vMarkusK** [comment]
Might you please verify this Script Block, do you see all Copy Jobs?

```
$HourstoCheck = 48
$allSesh = Get-VBRBackupSession  
$seshListBkc = @($allSesh | Where-Object{($_.CreationTime -ge (Get-Date).AddHours(-$HourstoCheck)) -and $_.JobType -match "BackupSync|SimpleBackupCopyWorker"})  
$seshListBkc
```

**Comment by OashaP** [comment]
This script successfully returned all of our Backup Copy Jobs as it's output.

**Comment by vMarkusK** [comment]
@OashaP Might you please verify #102 ?

**Comment by OashaP** [comment]
The script works and our sensors now display the backup copies correctly.
Thank you for your help!
