### ISSUE TITLE
Veeam Backu V12 XML: Structural error in xml file, 2 open items. -- JSON: Das zurückgelieferte JSON entspricht nicht der erwarteten Struktur (Invalid JSON.). (Code: PE231)

### ISSUE THREAD

**Issue by joergbruse** [vMarkusK/Advanced-PRTG-Sensors#97]
I just upgraded to V12 ov Veeam B&R and got this error

XML: Structural error in xml file, 2 open items. -- JSON: Das zurückgelieferte JSON entspricht nicht der erwarteten Struktur (Invalid JSON.). (Code: PE231)

Probe Server and Veeam Server are different Servers. Console on PRTG Server is also updated to V12.

Script opened directly in Powershell on PRTG Server runs fine

Successful Backups      : 1
Warning Backups         : 0
Failes Backups          : 0
Failed Backups          : 0
Running Backups         : 0
Total Backup Transfer   : 20
Total Backup Read       : 550
Warning BackupCopys     : 0
Failes BackupCopys      : 0
Failed BackupCopys      : 0
Running BackupCopys     : 0
Idle BackupCopys        : 1
Successful Replications : 0
Warning Replications    : 0
Failes Replications     : 0
Failed Replications     : 0
Running Replications    : 0
Seccessful Endpoints    : 0
Warning Endpoints       : 0
Failes Endpoints        : 0
Running Endpoints       : 0

<prtg><result>
                <channel>Successful-Backups</channel>
                <value>1</value>
                <showChart>1</showChart>
                <showTable>1</showTable>
                </result><result>
                <channel>Warning-Backups</channel>
                <value>0</value>
                <showChart>1</showChart>
                <showTable>1</showTable>
                <LimitMaxWarning>0</LimitMaxWarning>
                <LimitMode>1</LimitMode>
                </result><result>
                <channel>Failes-Backups</channel>
                <value>0</value>
                <showChart>1</showChart>
                <showTable>1</showTable>
                <LimitMaxError>0</LimitMaxError>
                <LimitMode>1</LimitMode>
                </result><result>
                <channel>Failed-Backups</channel>
                <value>0</value>
                <showChart>1</showChart>
                <showTable>1</showTable>
                <LimitMaxError>0</LimitMaxError>
                <LimitMode>1</LimitMode>
                </result><result>
                <channel>Running-Backups</channel>
                <value>0</value>
                <showChart>1</showChart>
                <showTable>1</showTable>
                </result><result>
                <channel>TotalBackupRead</channel>
                <value>550</value>
                <unit>Custom</unit>
                <customUnit>GB</customUnit>
                <showChart>1</showChart>
                <showTable>1</showTable>
                </result><result>
                <channel>TotalBackupTransfer</channel>
                <value>20</value>
                <unit>Custom</unit>
                <customUnit>GB</customUnit>
                <showChart>1</showChart>
                <showTable>1</showTable>
                </result><result>
                <channel>Successful-BackupCopys</channel>
                <value>1</value>
                <showChart>1</showChart>
                <showTable>1</showTable>
                </result><result>
                <channel>Warning-BackupCopys</channel>
                <value>0</value>
                <showChart>1</showChart>
                <showTable>1</showTable>
                <LimitMaxWarning>0</LimitMaxWarning>
                <LimitMode>1</LimitMode>
                </result><result>
                <channel>Failes-BackupCopys</channel>
                <value>0</value>
                <showChart>1</showChart>
                <showTable>1</showTable>
                <LimitMaxError>0</LimitMaxError>
                <LimitMode>1</LimitMode>
                </result><result>
                <channel>Failed-BackupCopys</channel>
                <value>0</value>
                <showChart>1</showChart>
                <showTable>1</showTable>
                <LimitMaxError>0</LimitMaxError>
                <LimitMode>1</LimitMode>
                </result><result>
                <channel>Running-BackupCopys</channel>
                <value>0</value>
                <showChart>1</showChart>
                <showTable>1</showTable>
                </result><result>
                <channel>Idle-BackupCopys</channel>
                <value>1</value>
                <showChart>1</showChart>
                <showTable>1</showTable>
                </result><result>
                <channel>Successful-Replications</channel>
                <value>0</value>
                <showChart>1</showChart>
                <showTable>1</showTable>
                </result><result>
                <channel>Warning-Replications</channel>
                <value>0</value>
                <showChart>1</showChart>
                <showTable>1</showTable>
                <LimitMaxWarning>0</LimitMaxWarning>
                <LimitMode>1</LimitMode>
                </result><result>
                <channel>Failes-Replications</channel>
                <value>0</value>
                <showChart>1</showChart>
                <showTable>1</showTable>
                <LimitMaxError>0</LimitMaxError>
                <LimitMode>1</LimitMode>
                </result><result>
                <channel>Failed-Replications</channel>
                <value>0</value>
                <showChart>1</showChart>
                <showTable>1</showTable>
                <LimitMaxError>0</LimitMaxError>
                <LimitMode>1</LimitMode>
                </result><result>
                <channel>Running-Replications</channel>
                <value>0</value>
                <showChart>1</showChart>
                <showTable>1</showTable>
                </result><result>
                <channel>Successful-Endpoints</channel>
                <value>0</value>
                <showChart>1</showChart>
                <showTable>1</showTable>
                </result><result>
                <channel>Warning-Endpoints</channel>
                <value>0</value>
                <showChart>1</showChart>
                <showTable>1</showTable>
                <LimitMaxWarning>0</LimitMaxWarning>
                <LimitMode>1</LimitMode>
                </result><result>
                <channel>Failes-Endpoints</channel>
                <value>0</value>
                <showChart>1</showChart>
                <showTable>1</showTable>
                <LimitMaxError>0</LimitMaxError>
                <LimitMode>1</LimitMode>
                </result><result>
                <channel>Running-Endpoints</channel>
                <value>0</value>
                <showChart>1</showChart>
                <showTable>1</showTable>
                </result><result>
            <channel>REPO - Default Backup Repository</channel>
            <value>9</value>
            <unit>Percent</unit>
            <showChart>1</showChart>
            <showTable>1</showTable>
            <LimitMinWarning>20</LimitMinWarning>
            <LimitMinError>10</LimitMinError>
            <LimitMode>1</LimitMode>
            </result><result>
            <channel>REPO - XXXXXXXXXXXXXX</channel>
            <value>79</value>
            <unit>Percent</unit>
            <showChart>1</showChart>
            <showTable>1</showTable>
            <LimitMinWarning>20</LimitMinWarning>
            <LimitMinError>10</LimitMinError>
            <LimitMode>1</LimitMode>
            </result><result>
            <channel>XXXXXXXXXXXl>
            <value>74</value>
            <unit>Percent</unit>
            <showChart>1</showChart>
            <showTable>1</showTable>
            <LimitMinWarning>20</LimitMinWarning>
            <LimitMinError>10</LimitMinError>
            <LimitMode>1</LimitMode>
            </result></prtg>

PS C:\Program Files (x86)\PRTG Network Monitor\Custom Sensors\EXEXML>

Im am using PRTG-VeeamBRStats-v3.ps1

I have some identical Setups with V11 working fine.

By the way, is there a scitpt for Monitoring Veeam 365 Backup ?

Any idea ?

best regards

Jörg

**Comment by vMarkusK** [comment]
Hi @joergbruse ,

at first, ist good to know that the script works with v12 GA. I have only verified it with RC Builds so far.

> Probe Server and Veeam Server are different Servers. Console on PRTG Server is also updated to V12.
> Script opened directly in Powershell on PRTG Server runs fine

Is the Probe Server another server or is the PRTG Master also the Probe for this sensor?
Please start and connect the Veeam B&R Console on all of the used PRTG Probes to make sure latest updates of the PS SnapIn are installed after the v12 update. I have seen some cases where a reboot was required after the update to make this work for all users on the server.

> Im am using PRTG-VeeamBRStats-v3.ps1

To get rid of maintaining Veeam Console in the PRTG Probe you can schedule a Windows Task on the Veeam B&R Server to push the Sensor data to the PRTG Server. Example:
`PRTG-VeeamBRStats-v3.ps1 -httppush:$true -httpserver 10.10.10.10 -httptoken 24A26A91-D292-4FF7-895D-B5E128A4D6C9 -httpport 5050`

> By the way, is there a scitpt for Monitoring Veeam 365 Backup ?

@jorgedlcruz is doing awesome work with his Grafana Dashboards: https://github.com/jorgedlcruz/veeam-backup-for-microsoft365-grafana
