### ISSUE TITLE
Error SyncSpaceInfoToDB 

### ISSUE THREAD

**Issue by premium3722** [vMarkusK/Advanced-PRTG-Sensors#98]
Good day

Thank you in advance for the great script !
We installed it on a server 2022 and now we get an error.
Server:   Windows Server 2022
Version:  Veeam V12
PRTG:     PRTG and Veeam are on the same Server

The script runs through and generates the XML but a message appears shortly before completion

Error:
Get-vPCRepoInfo : Ausnahme beim Aufrufen von "SyncSpaceInfoToDb" mit 2 Argument(en):  "Failed to find valid gateway server for non-scheduled 
repository Offline Backup ([IP OF SERVER]): [NAME OF SERVER] Failed to check whether file or folder \\[IP FROM BACKUP NAS]\backup exists."
In C:\Program Files (x86)\PRTG Network Monitor\Custom Sensors\EXEXML\PRTG-VeeamBRStats.ps1:624 Zeichen:29
+     $RepoData = $repoList | Get-vPCRepoInfo
+                             ~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-vPCRepoInfo

I think the problem is that this job is disabled. This is only activated 1-2 times a year. Could this be avoided?

Thanks!

**Comment by vMarkusK** [comment]
Hi @premium3722 ,

what type of repo is that? Is it offline?

Might you please share the Result of the Script Block:
```
[Array]$AllRepos = Get-VBRBackupRepository | Where-Object {$_.Type -notmatch "SanSnapshotOnly"}    # Get all Repositories Except SAN
[Array]$CloudRepos = $AllRepos | Where-Object {$_.Type -match "Cloud"}    # Get all Cloud Repositories
[Array]$repoList = $AllRepos | Where-Object {$_.Type -notmatch "Cloud"}    # Get all Repositories Except SAN and Cloud
[Array]$scaleouts = Get-VBRBackupRepository -scaleout
if ($scaleouts) {
    foreach ($scaleout in $scaleouts) {
        $extents = Get-VBRRepositoryExtent -Repository $scaleout
        foreach ($ex in $extents) {
            $repoList = $repoList + $ex.repository
        }
    }
}
$repoList | Format-Table -AutoSize
```

**Comment by premium3722** [comment]
![veeam](https://user-images.githubusercontent.com/18242867/223393009-4b5718c9-dd9a-4daf-b8cc-babcad7c60af.png)


Hello @vMarkusK 

Thank you for taking the time to do this! I admire the commitment of open source very much!
I ran the script block and this is what came up (Some censored ip's etc)

Yes it is an offline repo that we turn on 1-2 times a year.


Thanks!

Kind Regards
Levin

**Comment by vMarkusK** [comment]
The only option I see is excluding unavailable repositories. Please verify #99

**Comment by premium3722** [comment]
Good morning
Thank you very much, it works now with the offline repo!

From my side the problem can be closed.
